### ISSUE TITLE
Strict Standards: Declaration of getReCAPTCHAtab::getDisplayRegistration()

### ISSUE THREAD

**Issue by akarat555** [iosoft/cb-recaptcha#39]
Strict Standards: Declaration of getReCAPTCHAtab::getDisplayRegistration() should be compatible with cbTabHandler::getDisplayRegistration($tab, $user, $ui, $postdata) in 
d:\xampp\htdocs\myproject.com\components\com_comprofiler\plugin\user\plug_cbrecaptcha\cb.recaptcha.php on line 248

community builder 2.1.3+build.2017
joomla 3.8.3

**Comment by FirstHard** [comment]
Will there be a solution to this problem? I have the same thing.

**Comment by iosoft** [comment]
> Will there be a solution to this problem? I have the same thing.

I am looking into this.

**Comment by iosoft** [comment]
@akarat555 and @FirstHard  

I have made a bug fix. Pls replace the files (using FTP) and let me know if you face any issue.
My test server is offline.
